# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gprox < Formula
  desc "A simple ssl proxy for local development"
  homepage "https://github.com/creedasaurus/gprox"
  version "0.3.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/creedasaurus/gprox/releases/download/v0.3.3/gprox_0.3.3_darwin_amd64.tar.gz"
      sha256 "603845a8d3f2d302a49d4e57f7031d928681e619c3cf5feb07e62af528713dde"
    end
    if Hardware::CPU.arm?
      url "https://github.com/creedasaurus/gprox/releases/download/v0.3.3/gprox_0.3.3_darwin_arm64.tar.gz"
      sha256 "450407def13231752db978ca9cde6b07893f98a69ff241ddc98538c620999fca"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/creedasaurus/gprox/releases/download/v0.3.3/gprox_0.3.3_linux_amd64.tar.gz"
      sha256 "81c95053686671de5c973ba506907024ba49162d00068bc9f9329f969e59776a"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/creedasaurus/gprox/releases/download/v0.3.3/gprox_0.3.3_linux_armv6.tar.gz"
      sha256 "fe854b1a40aceb8f644eec301c939a0c2b6f96d11222421831cbd7b6ce5e4709"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/creedasaurus/gprox/releases/download/v0.3.3/gprox_0.3.3_linux_arm64.tar.gz"
      sha256 "14711839488a2ce1ad62495d54c464fb4e1f68437cce9ae5ab09783128fe8ad7"
    end
  end

  def install
    bin.install "gprox"
  end

  def caveats; <<~EOS
    Try gprox --help
  EOS
  end

  test do
    system "#{bin} --version"
  end
end
