# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gprox < Formula
  desc "A simple ssl proxy for local development"
  homepage "https://github.com/creedasaurus/gprox"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/creedasaurus/gprox/releases/download/0.3.4/gprox_0.3.4_darwin_arm64.tar.gz"
      sha256 "99908f16e7e223d75f8f3f6f2472e91feee1e512dd16d28671b34616d3353520"

      def install
        bin.install "gprox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/creedasaurus/gprox/releases/download/0.3.4/gprox_0.3.4_darwin_amd64.tar.gz"
      sha256 "8bb041b033ea6e076699dc97908980accaae90fdc85552df837642dd56f24b7b"

      def install
        bin.install "gprox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/creedasaurus/gprox/releases/download/0.3.4/gprox_0.3.4_linux_amd64.tar.gz"
      sha256 "72f2548560c0fc0c5ddc201b6a30dd2d27198697aa3de2fa174c390988065ad7"

      def install
        bin.install "gprox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/creedasaurus/gprox/releases/download/0.3.4/gprox_0.3.4_linux_arm64.tar.gz"
      sha256 "809cb90c97c6971e5d6d4ecf3b8e1b045fcf98be9f63264e1f9cb15ef463ea37"

      def install
        bin.install "gprox"
      end
    end
  end

  def caveats; <<~EOS
    Try gprox --help
  EOS
  end

  test do
    system "#{bin} --version"
  end
end
